hs.hotkey.bind({}, "F15", function()
    hs.application.launchOrFocus("Chromium")
end)
hs.hotkey.bind({}, "F14", function()
    hs.application.launchOrFocus("Yandex")
end)
hs.hotkey.bind({}, "F13", function()
    hs.application.launchOrFocus("WebStorm")
end)
hs.hotkey.bind({}, "F16", function()
    hs.application.launchOrFocus("iTerm")
end)
